version: "2"

linters:
  enable:
    - bodyclose
    # - exhaustive
    # - goconst
    # - godot
    # - godox
    # - gomoddirectives
    - goprintffuncname
    # - gosec
    - misspell
    # - nakedret
    # - nestif
    # - nilerr
    - noctx
    - nolintlint
    # - prealloc
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    # - unconvert
    # - unparam
    - whitespace
    # - wrapcheck
  disable:
    - errcheck
    - ineffassign
    - unused
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx
  settings:
    depguard:
      rules:
        profile-service:
          list-mode: lax
          files:
            - "profile-service/**"
          allow:
            - $gostd
          deny:
            - pkg: "app/server"
              desc: "application layer must not depend on HTTP wiring"
            - pkg: "app/api"
              desc: "application layer must not depend on transport models"
            - pkg: "app/db/postgres"
              desc: "application layer should depend on db ports, not adapter impls"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
