// Package echo_profile_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package echo_profile_api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CursorMetaMode.
const (
	Cursor CursorMetaMode = "cursor"
)

// Defines values for OffsetMetaMode.
const (
	Offset OffsetMetaMode = "offset"
)

// CursorMeta defines model for CursorMeta.
type CursorMeta struct {
	// Etags Mapping of item UUIDs to their ETags for optimistic concurrency control
	Etags *map[string]string `json:"etags,omitempty"`
	Limit int                `json:"limit"`
	Links *struct {
		Next *string `json:"next,omitempty"`
		Prev *string `json:"prev,omitempty"`
	} `json:"links,omitempty"`
	Mode       CursorMetaMode `json:"mode"`
	NextCursor *string        `json:"nextCursor,omitempty"`
	PrevCursor *string        `json:"prevCursor,omitempty"`
	RequestId  *string        `json:"requestId,omitempty"`
	TraceId    *string        `json:"traceId,omitempty"`
}

// CursorMetaMode defines model for CursorMeta.Mode.
type CursorMetaMode string

// ETagValue defines model for ETagValue.
type ETagValue = string

// OffsetMeta defines model for OffsetMeta.
type OffsetMeta struct {
	// Etags Mapping of item UUIDs to their ETags for optimistic concurrency control
	Etags *map[string]string `json:"etags,omitempty"`
	Links *struct {
		Next *string `json:"next,omitempty"`
		Prev *string `json:"prev,omitempty"`
	} `json:"links,omitempty"`
	Mode       OffsetMetaMode `json:"mode"`
	Page       int            `json:"page"`
	PageSize   int            `json:"pageSize"`
	RequestId  *string        `json:"requestId,omitempty"`
	TotalItems int            `json:"totalItems"`
	TotalPages int            `json:"totalPages"`
	TraceId    *string        `json:"traceId,omitempty"`
}

// OffsetMetaMode defines model for OffsetMeta.Mode.
type OffsetMetaMode string

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	union json.RawMessage
}

// Problem defines model for Problem.
type Problem struct {
	Code          *string `json:"code,omitempty"`
	Detail        *string `json:"detail,omitempty"`
	Instance      *string `json:"instance,omitempty"`
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalidParams,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	TraceId              *string                `json:"traceId,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Profile defines model for Profile.
type Profile struct {
	Age       *string                                `json:"age,omitempty"`
	CreatedAt *time.Time                             `json:"createdAt,omitempty"`
	Email     nullable.Nullable[openapi_types.Email] `json:"email,omitempty"`
	Id        openapi_types.UUID                     `json:"id"`
	Name      string                                 `json:"name"`
}

// SuccessEnvelopeList defines model for SuccessEnvelopeList.
type SuccessEnvelopeList struct {
	Data []interface{}  `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// SuccessEnvelopeSingle defines model for SuccessEnvelopeSingle.
type SuccessEnvelopeSingle struct {
	Data interface{} `json:"data"`
	Meta struct {
		RequestId *string `json:"requestId,omitempty"`
		TraceId   *string `json:"traceId,omitempty"`
	} `json:"meta"`
}

// SuccessProfile defines model for SuccessProfile.
type SuccessProfile struct {
	Data Profile `json:"data"`
	Meta struct {
		RequestId *string `json:"requestId,omitempty"`
		TraceId   *string `json:"traceId,omitempty"`
	} `json:"meta"`
}

// SuccessProfileList defines model for SuccessProfileList.
type SuccessProfileList struct {
	Data []Profile      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// CursorAfter defines model for CursorAfter.
type CursorAfter = string

// CursorBefore defines model for CursorBefore.
type CursorBefore = string

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProfileId defines model for ProfileId.
type ProfileId = openapi_types.UUID

// RequiredIfMatch defines model for RequiredIfMatch.
type RequiredIfMatch = ETagValue

// PreconditionFailedResponse defines model for PreconditionFailedResponse.
type PreconditionFailedResponse = Problem

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// CreateProfile defines model for CreateProfile.
type CreateProfile struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  string               `json:"name"`
}

// ModifyProfile defines model for ModifyProfile.
type ModifyProfile struct {
	Age   nullable.Nullable[string] `json:"age,omitempty"`
	Email *openapi_types.Email      `json:"email,omitempty"`
	Name  nullable.Nullable[string] `json:"name,omitempty"`
}

// ListProfilesParams defines parameters for ListProfiles.
type ListProfilesParams struct {
	// Page 0-based page number (use with `pageSize`)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Page size (use with `page`)
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// After Opaque cursor returned by the previous response (use with `limit`)
	After *CursorAfter `form:"after,omitempty" json:"after,omitempty"`

	// Before Opaque cursor returned by the previous response (use with `limit`)
	Before *CursorBefore `form:"before,omitempty" json:"before,omitempty"`

	// Limit Page size for cursor pagination (use with `cursor`)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateProfileJSONBody defines parameters for CreateProfile.
type CreateProfileJSONBody struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  string               `json:"name"`
}

// DeleteProfileParams defines parameters for DeleteProfile.
type DeleteProfileParams struct {
	// IfMatch Match against current entity tag to allow update
	IfMatch RequiredIfMatch `json:"If-Match"`
}

// ModifyProfileJSONBody defines parameters for ModifyProfile.
type ModifyProfileJSONBody struct {
	Age   nullable.Nullable[string] `json:"age,omitempty"`
	Email *openapi_types.Email      `json:"email,omitempty"`
	Name  nullable.Nullable[string] `json:"name,omitempty"`
}

// ModifyProfileParams defines parameters for ModifyProfile.
type ModifyProfileParams struct {
	// IfMatch Match against current entity tag to allow update
	IfMatch RequiredIfMatch `json:"If-Match"`
}

// UpdateProfileJSONBody defines parameters for UpdateProfile.
type UpdateProfileJSONBody struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  string               `json:"name"`
}

// UpdateProfileParams defines parameters for UpdateProfile.
type UpdateProfileParams struct {
	// IfMatch Match against current entity tag to allow update
	IfMatch RequiredIfMatch `json:"If-Match"`
}

// CreateProfileJSONRequestBody defines body for CreateProfile for application/json ContentType.
type CreateProfileJSONRequestBody CreateProfileJSONBody

// ModifyProfileJSONRequestBody defines body for ModifyProfile for application/json ContentType.
type ModifyProfileJSONRequestBody ModifyProfileJSONBody

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody UpdateProfileJSONBody

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["invalidParams"]; found {
		err = json.Unmarshal(raw, &a.InvalidParams)
		if err != nil {
			return fmt.Errorf("error reading 'invalidParams': %w", err)
		}
		delete(object, "invalidParams")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["traceId"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'traceId': %w", err)
		}
		delete(object, "traceId")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.InvalidParams != nil {
		object["invalidParams"], err = json.Marshal(a.InvalidParams)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'invalidParams': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	if a.TraceId != nil {
		object["traceId"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traceId': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsOffsetMeta returns the union data inside the PaginationMeta as a OffsetMeta
func (t PaginationMeta) AsOffsetMeta() (OffsetMeta, error) {
	var body OffsetMeta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOffsetMeta overwrites any union data inside the PaginationMeta as the provided OffsetMeta
func (t *PaginationMeta) FromOffsetMeta(v OffsetMeta) error {
	v.Mode = "offset"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOffsetMeta performs a merge with any union data inside the PaginationMeta, using the provided OffsetMeta
func (t *PaginationMeta) MergeOffsetMeta(v OffsetMeta) error {
	v.Mode = "offset"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCursorMeta returns the union data inside the PaginationMeta as a CursorMeta
func (t PaginationMeta) AsCursorMeta() (CursorMeta, error) {
	var body CursorMeta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCursorMeta overwrites any union data inside the PaginationMeta as the provided CursorMeta
func (t *PaginationMeta) FromCursorMeta(v CursorMeta) error {
	v.Mode = "cursor"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCursorMeta performs a merge with any union data inside the PaginationMeta, using the provided CursorMeta
func (t *PaginationMeta) MergeCursorMeta(v CursorMeta) error {
	v.Mode = "cursor"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PaginationMeta) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PaginationMeta) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cursor":
		return t.AsCursorMeta()
	case "offset":
		return t.AsOffsetMeta()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PaginationMeta) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PaginationMeta) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(ctx echo.Context) error
	// List profiles (offset or cursor pagination)
	// (GET /v1/profiles)
	ListProfiles(ctx echo.Context, params ListProfilesParams) error
	// Create a profile
	// (POST /v1/profiles)
	CreateProfile(ctx echo.Context) error
	// Delete a profile
	// (DELETE /v1/profiles/{id})
	DeleteProfile(ctx echo.Context, id ProfileId, params DeleteProfileParams) error
	// Get profile by ID
	// (GET /v1/profiles/{id})
	GetProfileById(ctx echo.Context, id ProfileId) error
	// Patch an existing profile
	// (PATCH /v1/profiles/{id})
	ModifyProfile(ctx echo.Context, id ProfileId, params ModifyProfileParams) error
	// Update an existing profile
	// (PUT /v1/profiles/{id})
	UpdateProfile(ctx echo.Context, id ProfileId, params UpdateProfileParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Healthz converts echo context to params.
func (w *ServerInterfaceWrapper) Healthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Healthz(ctx)
	return err
}

// ListProfiles converts echo context to params.
func (w *ServerInterfaceWrapper) ListProfiles(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProfilesParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", ctx.QueryParams(), &params.After)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter after: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameter("form", true, false, "before", ctx.QueryParams(), &params.Before)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProfiles(ctx, params)
	return err
}

// CreateProfile converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProfile(ctx)
	return err
}

// DeleteProfile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProfileId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteProfileParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch RequiredIfMatch
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-Match: %s", err))
		}

		params.IfMatch = IfMatch
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter If-Match is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProfile(ctx, id, params)
	return err
}

// GetProfileById converts echo context to params.
func (w *ServerInterfaceWrapper) GetProfileById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProfileId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProfileById(ctx, id)
	return err
}

// ModifyProfile converts echo context to params.
func (w *ServerInterfaceWrapper) ModifyProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProfileId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ModifyProfileParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch RequiredIfMatch
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-Match: %s", err))
		}

		params.IfMatch = IfMatch
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter If-Match is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ModifyProfile(ctx, id, params)
	return err
}

// UpdateProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProfileId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProfileParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch RequiredIfMatch
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-Match: %s", err))
		}

		params.IfMatch = IfMatch
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter If-Match is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProfile(ctx, id, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/healthz", wrapper.Healthz)
	router.GET(baseURL+"/v1/profiles", wrapper.ListProfiles)
	router.POST(baseURL+"/v1/profiles", wrapper.CreateProfile)
	router.DELETE(baseURL+"/v1/profiles/:id", wrapper.DeleteProfile)
	router.GET(baseURL+"/v1/profiles/:id", wrapper.GetProfileById)
	router.PATCH(baseURL+"/v1/profiles/:id", wrapper.ModifyProfile)
	router.PUT(baseURL+"/v1/profiles/:id", wrapper.UpdateProfile)

}

type PreconditionFailedResponseResponseHeaders struct {
	ETag ETagValue
}
type PreconditionFailedResponseApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers PreconditionFailedResponseResponseHeaders
}

type ProblemResponseApplicationProblemPlusJSONResponse Problem

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz204Response struct {
}

func (response Healthz204Response) VisitHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ListProfilesRequestObject struct {
	Params ListProfilesParams
}

type ListProfilesResponseObject interface {
	VisitListProfilesResponse(w http.ResponseWriter) error
}

type ListProfiles200ResponseHeaders struct {
	ETag string
	Link string
}

type ListProfiles200JSONResponse struct {
	Body    SuccessProfileList
	Headers ListProfiles200ResponseHeaders
}

func (response ListProfiles200JSONResponse) VisitListProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("Link", fmt.Sprint(response.Headers.Link))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListProfiles400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response ListProfiles400ApplicationProblemPlusJSONResponse) VisitListProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListProfiles401ApplicationProblemPlusJSONResponse Problem

func (response ListProfiles401ApplicationProblemPlusJSONResponse) VisitListProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListProfiles429ApplicationProblemPlusJSONResponse Problem

func (response ListProfiles429ApplicationProblemPlusJSONResponse) VisitListProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type ListProfilesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListProfilesdefaultApplicationProblemPlusJSONResponse) VisitListProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateProfileRequestObject struct {
	Body *CreateProfileJSONRequestBody
}

type CreateProfileResponseObject interface {
	VisitCreateProfileResponse(w http.ResponseWriter) error
}

type CreateProfile201ResponseHeaders struct {
	Location string
}

type CreateProfile201JSONResponse struct {
	Body    SuccessProfile
	Headers CreateProfile201ResponseHeaders
}

func (response CreateProfile201JSONResponse) VisitCreateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateProfile400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response CreateProfile400ApplicationProblemPlusJSONResponse) VisitCreateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProfile422ApplicationProblemPlusJSONResponse Problem

func (response CreateProfile422ApplicationProblemPlusJSONResponse) VisitCreateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateProfiledefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateProfiledefaultApplicationProblemPlusJSONResponse) VisitCreateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteProfileRequestObject struct {
	Id     ProfileId `json:"id"`
	Params DeleteProfileParams
}

type DeleteProfileResponseObject interface {
	VisitDeleteProfileResponse(w http.ResponseWriter) error
}

type DeleteProfile204Response struct {
}

func (response DeleteProfile204Response) VisitDeleteProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProfile400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response DeleteProfile400ApplicationProblemPlusJSONResponse) VisitDeleteProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProfile404ApplicationProblemPlusJSONResponse Problem

func (response DeleteProfile404ApplicationProblemPlusJSONResponse) VisitDeleteProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProfile412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedResponseApplicationProblemPlusJSONResponse
}

func (response DeleteProfile412ApplicationProblemPlusJSONResponse) VisitDeleteProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(412)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteProfiledefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteProfiledefaultApplicationProblemPlusJSONResponse) VisitDeleteProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfileByIdRequestObject struct {
	Id ProfileId `json:"id"`
}

type GetProfileByIdResponseObject interface {
	VisitGetProfileByIdResponse(w http.ResponseWriter) error
}

type GetProfileById200ResponseHeaders struct {
	ETag ETagValue
}

type GetProfileById200JSONResponse struct {
	Body    SuccessProfile
	Headers GetProfileById200ResponseHeaders
}

func (response GetProfileById200JSONResponse) VisitGetProfileByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProfileById400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response GetProfileById400ApplicationProblemPlusJSONResponse) VisitGetProfileByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileById404ApplicationProblemPlusJSONResponse Problem

func (response GetProfileById404ApplicationProblemPlusJSONResponse) VisitGetProfileByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileByIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProfileByIddefaultApplicationProblemPlusJSONResponse) VisitGetProfileByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ModifyProfileRequestObject struct {
	Id     ProfileId `json:"id"`
	Params ModifyProfileParams
	Body   *ModifyProfileJSONRequestBody
}

type ModifyProfileResponseObject interface {
	VisitModifyProfileResponse(w http.ResponseWriter) error
}

type ModifyProfile200JSONResponse SuccessProfile

func (response ModifyProfile200JSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ModifyProfile400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response ModifyProfile400ApplicationProblemPlusJSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ModifyProfile404ApplicationProblemPlusJSONResponse Problem

func (response ModifyProfile404ApplicationProblemPlusJSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ModifyProfile412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedResponseApplicationProblemPlusJSONResponse
}

func (response ModifyProfile412ApplicationProblemPlusJSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(412)

	return json.NewEncoder(w).Encode(response.Body)
}

type ModifyProfile422ApplicationProblemPlusJSONResponse Problem

func (response ModifyProfile422ApplicationProblemPlusJSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ModifyProfiledefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ModifyProfiledefaultApplicationProblemPlusJSONResponse) VisitModifyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateProfileRequestObject struct {
	Id     ProfileId `json:"id"`
	Params UpdateProfileParams
	Body   *UpdateProfileJSONRequestBody
}

type UpdateProfileResponseObject interface {
	VisitUpdateProfileResponse(w http.ResponseWriter) error
}

type UpdateProfile200ResponseHeaders struct {
	ETag ETagValue
}

type UpdateProfile200JSONResponse struct {
	Body    SuccessProfile
	Headers UpdateProfile200ResponseHeaders
}

func (response UpdateProfile200JSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateProfile400ApplicationProblemPlusJSONResponse struct {
	ProblemResponseApplicationProblemPlusJSONResponse
}

func (response UpdateProfile400ApplicationProblemPlusJSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProfile404ApplicationProblemPlusJSONResponse Problem

func (response UpdateProfile404ApplicationProblemPlusJSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProfile412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedResponseApplicationProblemPlusJSONResponse
}

func (response UpdateProfile412ApplicationProblemPlusJSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(412)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateProfile422ApplicationProblemPlusJSONResponse Problem

func (response UpdateProfile422ApplicationProblemPlusJSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProfiledefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateProfiledefaultApplicationProblemPlusJSONResponse) VisitUpdateProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// List profiles (offset or cursor pagination)
	// (GET /v1/profiles)
	ListProfiles(ctx context.Context, request ListProfilesRequestObject) (ListProfilesResponseObject, error)
	// Create a profile
	// (POST /v1/profiles)
	CreateProfile(ctx context.Context, request CreateProfileRequestObject) (CreateProfileResponseObject, error)
	// Delete a profile
	// (DELETE /v1/profiles/{id})
	DeleteProfile(ctx context.Context, request DeleteProfileRequestObject) (DeleteProfileResponseObject, error)
	// Get profile by ID
	// (GET /v1/profiles/{id})
	GetProfileById(ctx context.Context, request GetProfileByIdRequestObject) (GetProfileByIdResponseObject, error)
	// Patch an existing profile
	// (PATCH /v1/profiles/{id})
	ModifyProfile(ctx context.Context, request ModifyProfileRequestObject) (ModifyProfileResponseObject, error)
	// Update an existing profile
	// (PUT /v1/profiles/{id})
	UpdateProfile(ctx context.Context, request UpdateProfileRequestObject) (UpdateProfileResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(ctx echo.Context) error {
	var request HealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx.Request().Context(), request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		return validResponse.VisitHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListProfiles operation middleware
func (sh *strictHandler) ListProfiles(ctx echo.Context, params ListProfilesParams) error {
	var request ListProfilesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProfiles(ctx.Request().Context(), request.(ListProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProfiles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProfilesResponseObject); ok {
		return validResponse.VisitListProfilesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProfile operation middleware
func (sh *strictHandler) CreateProfile(ctx echo.Context) error {
	var request CreateProfileRequestObject

	var body CreateProfileJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProfile(ctx.Request().Context(), request.(CreateProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateProfileResponseObject); ok {
		return validResponse.VisitCreateProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProfile operation middleware
func (sh *strictHandler) DeleteProfile(ctx echo.Context, id ProfileId, params DeleteProfileParams) error {
	var request DeleteProfileRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProfile(ctx.Request().Context(), request.(DeleteProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteProfileResponseObject); ok {
		return validResponse.VisitDeleteProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProfileById operation middleware
func (sh *strictHandler) GetProfileById(ctx echo.Context, id ProfileId) error {
	var request GetProfileByIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfileById(ctx.Request().Context(), request.(GetProfileByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfileById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProfileByIdResponseObject); ok {
		return validResponse.VisitGetProfileByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ModifyProfile operation middleware
func (sh *strictHandler) ModifyProfile(ctx echo.Context, id ProfileId, params ModifyProfileParams) error {
	var request ModifyProfileRequestObject

	request.Id = id
	request.Params = params

	var body ModifyProfileJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ModifyProfile(ctx.Request().Context(), request.(ModifyProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ModifyProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ModifyProfileResponseObject); ok {
		return validResponse.VisitModifyProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProfile operation middleware
func (sh *strictHandler) UpdateProfile(ctx echo.Context, id ProfileId, params UpdateProfileParams) error {
	var request UpdateProfileRequestObject

	request.Id = id
	request.Params = params

	var body UpdateProfileJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProfile(ctx.Request().Context(), request.(UpdateProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProfileResponseObject); ok {
		return validResponse.VisitUpdateProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
