{
 "title": "Coroot namespace",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{container_id!=\"\",cluster_name=~\"$cluster\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\")))"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(group by (container_id) (container_restarts_total{container_id=~\".+?${namespace}\\\\/.+?$\",cluster_name=~\"$cluster\"}))"
    }
   },
   {
    "name": "excl_namespace",
    "query": {
     "query": "query_result(group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{container_id!=\"\",cluster_name=~\"$cluster\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\")))"
    }
   },
   {
    "name": "top",
    "label": "Panel results limit (default 50)",
    "query": "50"
   },
   {
    "name": "technology",
    "query": {
     "query": "query_result((  group by (__name__, technology) (    label_replace(      label_replace(        {          __name__!~\"container_(dns|http|log).+_total\",          __name__=~\"container.+_(queries|requests|messages)_total\",          container_id=~\"/k8s/$namespace/.+\" or container_id=~\"/$namespace/.+\",cluster_name=~\"$cluster\"},        \"real_namespace\", \"$1\", \"container_id\", \"/k8s/([^/]+)/\"      ),      \"technology\", \"$1\", \"__name__\", \"container_(.+?)_(?:queries|requests|messages)_total\"    ) > 0  )))"
    }
   }
  ]
 },
 "panels": [
  { "title": "data stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "technology",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_set(vector(1),\"tech\",\"${technology}\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "group by (container_id,namespace,service) (label_replace(label_replace(label_set(container_restarts_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?\\\\/$service$\"},\"namespace\",\"system.slice\"),\"namespace\",\"$1\",\"container_id\",\"\\\\/.+?\\\\/(.+?)\\\\/.*\"),\"service\",\"$1\",\"container_id\",\".*\\\\/(.+?)$\"))\n#group by (container_id,application_type) (container_application_type{container_id=~\".+?calico-node$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (container_id,application_type) (container_application_type{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?\\\\/$service$\"})\n#group by (container_id,application_type) (container_application_type{container_id=~\".+?calico-node$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "WITH (\n  metric = max by (source, actual_destination, status) (\n    label_replace(\n      sum by (container_id, actual_destination) (\n        rate(container_http_requests_total{cluster_name=~\"$cluster\", container_id=~\"\\\\/k8s.*\", status!~\"2..\"}[1m])\n      ) / on (container_id, actual_destination)\n      sum by (container_id, actual_destination) (\n        rate(container_http_requests_total{container_id=~\"\\\\/k8s.*\"}[1m])\n      ),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    )\n    or label_replace(\n      sum by (container_id, actual_destination) (\n        rate(container_http_requests_total{cluster_name=~\"$cluster\", container_id=~\"\\\\/system.*\", status!~\"2..\"}[1m])\n      ) / on (container_id, actual_destination)\n      sum by (container_id, actual_destination) (\n        rate(container_http_requests_total{container_id=~\"\\\\/system.*\"}[1m])\n      ),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ),\n  edges_query = group by (source, actual_destination, target_namespace, target_pod, target_service) (\n    label_replace(\n      label_copy(\n        coroot:http_requests{\n          target_namespace=~\"$namespace\",\n          target_service=~\"$service\"\n        },\n        \"source_pod\", \"source\"\n      ),\n      \"actual_destination\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  )\n)\n\nmax by (container_id) (\n  (\n    metric * on(source, actual_destination)\n    group_left(target_namespace, target_pod, target_service)\n    edges_query\n  )\n  * on(target_pod) group_left(container_id) (\n    group by (target_pod, container_id) (\n      label_replace(\n        container_restarts_total{cluster_name=~\"$cluster\", container_id=~\"\\\\/k.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      )\n      or on (target_pod, container_id) label_replace(\n        container_restarts_total{cluster_name=~\"$cluster\", container_id=~\"\\\\/system.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/sys.+?\\\\/(.+?)$\"\n      )\n    )\n  )\n)",
     "legendFormat": "errors"
    },
    {
     "expr": "\nWITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      max_over_time(histogram_quantile(0.95, sum by (le, container_id,actual_destination)(\n    rate( container_http_requests_duration_seconds_total_bucket{cluster_name=~\"$cluster\"}[$__interval]))\n    )[$__range]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n     max_over_time(histogram_quantile(0.95, sum by (le, container_id,actual_destination)(\n    rate( container_http_requests_duration_seconds_total_bucket{cluster_name=~\"$cluster\"}[$__interval]))\n    )[$__range]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            #coroot:http_requests{source_namespace=~\"metricsedge\", source_service=~\".*\", target_namespace!~\"(monitoring|system\\\\.slice)\"} or on (source_pod,actual_destination) I think we do not inspect around the selected namespace\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\nmax by (container_id) ((metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query) * on(target_pod) group_left(container_id)\ngroup by (target_pod,container_id) (\n    label_replace(\n        container_restarts_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or on (target_pod,container_id) label_replace(\n        container_restarts_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.*\"},\n        \"target_pod\", \"$1\", \"container_id\", \"\\\\/sys.+?\\\\/(.+?)$\"\n    )\n    ))",
     "legendFormat": "response time 95%%"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_restarts_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "errors"
    },
    {
     "expr": "range_max(rate(max by (container_id) (container_resources_cpu_throttled_seconds_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "errors"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_oom_kills_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_resources_disk_delay_seconds_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_net_latency_seconds{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_max(increase(max by (container_id) (container_net_tcp_retransmits_total{cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "range_sum(increase(sum by (container_id) (container_log_messages_total{cluster_name=~\"$cluster\",level=\"error\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])/range_sum(increase(sum by (container_id) (container_log_messages_total{ cluster_name=~\"$cluster\", container_id=~\".+?$namespace\\\\/.+?$\", container_id=~\".+?$service$\"})[1m])[$__range])",
     "legendFormat": "oom"
    },
    {
     "expr": "(\n  sum by (container_id) (rate(container_http_requests_total{cluster_name=~\"$cluster\", container_id=~\".*?$namespace\\\\/.*?$\", container_id=~\".*?\\\\/$service$\", status!~\"2..\"}[$__rate_interval]))\n  /\n  sum by (container_id) (rate(container_http_requests_total{cluster_name=~\"$cluster\", container_id=~\".*?$namespace\\\\/.*?$\", container_id=~\".*?\\\\/$service$\"}[$__rate_interval]))\n)",
     "legendFormat": "error out"
    },
    {
     "expr": "max_over_time(\n  histogram_quantile(0.95,\n    sum by (le, container_id) (\n      rate(container_http_requests_duration_seconds_total_bucket{\n        cluster_name=~\"$cluster\",\n        container_id=~\".*?$namespace\\\\/.+?$\",\n        container_id=~\".*?\\\\/$service$\"\n      }[$__interval])\n    )\n  )[$__range]\n)",
     "legendFormat": "error out"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "All connections of the selected object (drops only for k8s entities)",
     "type": "nodeGraph",
     "description": "The chart shows active connections for the object or those that existed during the dashboard's selected period. \nIt finds any outgoing connections from the object. Inside it displays the number of dropped packets in absolute values.\nIt finds incoming connections only if they originated from objects monitored by Coroot.",
     "gridPos": { "h": 49, "w": 7, "x": 0, "y": 732 },
     "targets": [
      {
       "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_cluster_name=~\"$cluster\", source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_cluster_name=~\"$cluster\", source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\nalias(base_query * on(id) group_right(title,subtitle,__name__) range_sum(\n    sum by (id) (\n      label_copy(\n        increase(\n          container_network_advance_tcp_stats_total{tcp_state=~\".*drop\"}[1m]\n        )\n        ,\"pod\",\"id\"\n      )\n    ) \n  [$__range]\n) or (base_query - 1),\"nodes\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "\nWITH (\n  metric = max by (source, actual_destination,target,id) (\n        label_replace(\n          rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n        ) or \n        label_replace(\n          rate(container_net_tcp_retransmits_total{container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n            \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n        )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service,target,id)(\n    label_join(\n      label_replace(\n          label_copy(\n              coroot:success_connections{source_cluster_name=~\"$cluster\", source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n              or on (source_pod,actual_destination)\n              coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n              \"source_pod\",\"source\",\"target_pod\",\"target\"\n          ),\n          \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n      ),\n      \"id\",\"+\",\"source\",\"target\"\n    )\n  )\n)\n\nalias(label_set(\n  max by (id,source,target) (\n   label_join(\n      label_copy(\n          (metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service,target,id) edges_query) >0\n      ,\"target_pod\",\"target\")\n  ,\"id\",\"+\",\"source\",\"target\"))\n,\"color\",\"red\",\"highlighted\",\"true\")\nor on (id,source,target) max by (id,source,target,color,highlighted) (\n  label_set(edges_query,\"color\",\"\",\"highlighted\",\"false\") * 0\n),\"edges\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network round-trip time, seconds (shows the $top slowest responses)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 732 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, destination_ip) (\n    label_replace(\n      increase(container_net_latency_seconds{cluster_name=~\"$cluster\", container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      increase(container_net_latency_seconds{cluster_name=~\"$cluster\", container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,destination_ip,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\", source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"destination_ip\",\"$1\",\"actual_destination\",\"(.+?):.*\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,destination_ip) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "TCP connection latency, seconds (shows the $top slowest responses)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 739 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "\n\nWITH (\n  metric = max by (source, destination) (\n      label_replace(\n        increase(container_net_tcp_connection_time_seconds_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_connection_time_seconds_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "Active TCP connections (shows the $top most numerous sessions)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        (container_net_tcp_active_connections{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        (container_net_tcp_active_connections{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "TCP connection attempts, per second (calculation may still be off) (shows the $top most frequent sessions)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 753 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        rate(container_net_tcp_active_connections{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        rate(container_net_tcp_active_connections{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "Traffic outbound/inbound bytes/sec (shows the $top highest-volume interactions)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 760 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "\n\n\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        increase(container_net_tcp_bytes_received_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_bytes_received_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "recv: {{source}} -> [{{target_namespace}}] {{target_pod}}"
      },
      {
       "expr": "\n\n\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        increase(container_net_tcp_bytes_sent_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        increase(container_net_tcp_bytes_sent_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n          \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "sent: {{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "TCP retransmissions, segments/second (shows the $top most frequent interactions)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 767 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\nWITH (\n  metric = max by (source, actual_destination) (\n      label_replace(\n        rate(container_net_tcp_retransmits_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k.*\"}[$__rate_interval]),\n         \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      ) or \n      label_replace(\n        rate(container_net_tcp_retransmits_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.slice.*\"}[$__rate_interval]),\n           \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n      )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))\n",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "TCP drops, packets/second (0 can mean metrics are missing) (shows the $top nodes by count)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 774 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\ntopk_max($top,alias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id) (\n      label_copy(\n        increase(\n          container_network_advance_tcp_stats_total{cluster_name=~\"$cluster\",tcp_state=~\".*drop\"}[1m]\n        )\n        ,\"pod\",\"id\"\n      )\n    ) \n  ,\"nodes\"))",
       "legendFormat": "{{id}} {{title}} {{subtitle}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application layer (HTTP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "All connections of the selected object (error%)",
     "type": "nodeGraph",
     "description": "The chart shows active connections for the object or those that existed during the dashboard's selected period. \nIt finds any outgoing connections from the object. Inside it displays the number of dropped packets in absolute values.\nIt finds incoming connections only if they originated from objects monitored by Coroot.",
     "gridPos": { "h": 35, "w": 7, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\n\nalias(\n    base_query * on(id) group_right(title,subtitle,__name__) \n    range_max(\n        max by (id) (\n            label_copy(\n                max by (container_id,actual_destination) (\n                    rate(container_http_requests_duration_seconds_total_sum{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})\n                ) * on(container_id,actual_destination) group_left(target_pod) group by (container_id,actual_destination,target_pod) (coroot:http_requests),\n                \"target_pod\",\"id\"\n            ) or\n            label_copy(\n                max by (container_id,actual_destination) (\n                    rate(container_http_requests_duration_seconds_total_sum{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.*\"})/rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/system.*\"})\n                )  * on(container_id,actual_destination) group_left(target_pod) group by (container_id,actual_destination,target_pod) (coroot:http_requests),\n                \"target_pod\",\"id\"\n            )\n        )\n    ) \n  [$__range]\n or (base_query - 1),\"nodes\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "alias(\n    group by(source,target,id)(\n        label_join(\n            label_copy(\n                coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"} \n                or\n                coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n                \"source_pod\",\"source\",\"target_pod\",\"target\"\n            ),\n            \"id\",\"+\",\"source\",\"target\"\n        )\n    )\n,\"edges\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Response time (shows the $top highest latencies)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_http_requests_duration_seconds_total_sum{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_duration_seconds_total_sum{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})/rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second (all codes) (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination) (\n    label_replace(\n      rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_duration_seconds_total_count{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second (200 codes) (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"2..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"2..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second (400 codes) (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"4..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"4..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second (500 codes) (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  metric = max by (source, actual_destination,status) (\n    label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"5..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n    ) or label_replace(\n      rate(container_http_requests_total{cluster_name=~\"$cluster\",container_id=~\"\\\\/k8s.*\", status=~\"5..\"})[$__rate_interval],\n      \"source\", \"$1\", \"container_id\", \"\\\\/system.slice\\\\/(.+?)$\"\n    )\n  ), \n  edges_query =  group by(source,actual_destination,target_namespace,target_pod,target_service)(\n    label_replace(\n        label_copy(\n            coroot:http_requests{source_cluster_name=~\"$cluster\",source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n            or on (source_pod,actual_destination)\n            coroot:http_requests{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"},\n            \"source_pod\",\"source\"\n        ),\n        \"actual_destination\",\"$1\",\"actual_destination\",\"(.+?)\"\n    )\n  )\n)\n\ntopk_max($top,(metric * on(source,actual_destination) group_left(target_namespace,target_pod,target_service) edges_query))",
       "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data layer (Kafka might sometimes be missing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "All connections of the selected object (drops only for k8s entities)",
     "type": "nodeGraph",
     "description": "The chart shows active connections for the object or those that existed during the dashboard's selected period. \nIt finds any outgoing connections from the object. Inside it displays the number of dropped packets in absolute values.\nIt finds incoming connections only if they originated from objects monitored by Coroot.",
     "gridPos": { "h": 88, "w": 7, "x": 0, "y": 717 },
     "targets": [
      {
       "expr": "WITH (\n  base_query = alias(\n    union(\n      (\n        group by (id, title, subtitle) (\n          # 1. Source standard\n          label_join(\n            label_copy(\n              coroot:statefuls{\n                source_cluster_name=~\"$cluster\",\n                source_namespace=~\"$namespace\",\n                source_service=~\"$service\",\n                target_namespace!~\"$excl_namespace\"\n              },\n              \"source_pod\", \"id\", \"source_pod\", \"title\"\n            ),\n            \"subtitle\", \" \", \"source_namespace\", \"source_service\"\n          )\n        )\n        or group by (id, title, subtitle) (\n          # 2. Target standard\n          label_join(\n            label_copy(\n              coroot:statefuls{\n                target_namespace=~\"$namespace\",\n                target_service=~\"$service\",\n                source_namespace!~\"$excl_namespace\"\n              },\n              \"target_pod\", \"id\", \"target_pod\", \"title\"\n            ),\n            \"subtitle\", \" \", \"target_namespace\", \"target_service\"\n          )\n        )\n      ),\n      (\n        group by (id, title, subtitle) (\n          # 3. Source->Target, target_namespace != \"empty\"\n          label_join(\n            label_copy(\n              coroot:statefuls{\n                source_cluster_name=~\"$cluster\",\n                source_namespace=~\"$namespace\",\n                source_service=~\"$service\",\n                target_namespace!~\"$excl_namespace\",\n                target_namespace!=\"empty\"\n              },\n              \"target_pod\", \"id\", \"target_pod\", \"title\"\n            ),\n            \"subtitle\", \" \", \"target_namespace\", \"target_service\"\n          )\n        )\n        or group by (id, title, subtitle) (\n          # 4. Source->Target, target_namespace == \"empty\"\n          label_join(\n            label_copy(\n              coroot:statefuls{\n                source_cluster_name=~\"$cluster\",\n                source_namespace=~\"$namespace\",\n                source_service=~\"$service\",\n                target_namespace=\"empty\"\n              },\n              \"actual_destination\", \"id\", \"actual_destination\", \"title\"\n            ),\n            \"subtitle\", \" \", \"target_type\"\n          )\n        )\n        or group by (id, title, subtitle) (\n          # 5. Target->Source standard\n          label_join(\n            label_copy(\n              coroot:statefuls{\n                target_namespace=~\"$namespace\",\n                target_service=~\"$service\",\n                source_namespace!~\"$excl_namespace\"\n              },\n              \"source_pod\", \"id\", \"source_pod\", \"title\"\n            ),\n            \"subtitle\", \" \", \"source_namespace\", \"source_service\"\n          )\n        )\n      )\n    )\n  , \"nodes\")\n)\n\nalias(\n  base_query * on(id) group_right(title, subtitle, __name__) range_sum(\n    sum by (id) (\n      label_copy(\n        increase(container_network_advance_tcp_stats_total{tcp_state=~\".*drop\"}[1m]),\n        \"pod\", \"id\"\n      )\n    )[$__range]\n  ) or (base_query - 1),\n  \"nodes\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "WITH (\n  edges_regular = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_join(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace!~\"$excl_namespace\",\n          target_namespace!=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace!~\"$excl_namespace\",\n          target_namespace!=\"empty\"\n        },\n        \"source_pod\", \"source\", \"target_pod\", \"target\"\n      ),\n      \"id\", \"+\", \"source\", \"target\"\n    )\n  ),\n  edges_empty = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_join(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace!~\"$excl_namespace\",\n          target_namespace=\"empty\"\n        },\n        \"source_pod\", \"source\", \"actual_destination\", \"target\"\n      ),\n      \"id\", \"+\", \"source\", \"target\"\n    )\n  )\n)\n\nalias(\n  max by (id, source, target) (edges_regular or edges_empty),\n\"edges\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$technology query duration time (shows the $top highest latencies)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 717 },
     "repeat": "technology",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "WITH (\n  edges_regular = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace!~\"$excl_namespace\",\n          target_namespace!=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace!=\"empty\"\n        },\n        \"source_pod\", \"source\", \"target_pod\", \"target\"\n      ),\n      \"actual_destination\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  edges_empty = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace=\"empty\"\n        },\n        \"source_pod\", \"source\", \"actual_destination\", \"target\"\n      ),\n      \"target_pod\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  metric = max by (source, actual_destination) (\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_duration_seconds_total_sum\", container_id=~\"\\\\/k8s\\\\/[^\\\\/]+\\\\/[^\\\\/]+\\\\/.*\"})\n        /\n        rate({__name__=~\"container_${technology}_(queries|requests)_duration_seconds_total_count\", container_id=~\"\\\\/k8s\\\\/[^\\\\/]+\\\\/[^\\\\/]+\\\\/.*\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/k8s\\\\/[^\\\\/]+\\\\/([^\\\\/]+)\\\\/.*\"\n      )\n    )\n    or\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_duration_seconds_total_sum\", container_id=~\"\\\\/system\\\\.slice\\\\/.*\"})\n        /\n        rate({__name__=~\"container_${technology}_(queries|requests)_duration_seconds_total_count\", container_id=~\"\\\\/system\\\\.slice\\\\/.*\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/system\\\\.slice\\\\/([^\\\\/]+)$\"\n      )\n    )\n  )\n)\n\ntopk_max(\n  $top,\n  (\n    metric\n    * on(source, actual_destination)\n    group_left(id, target, target_namespace, target_pod, target_service)\n    (edges_regular or edges_empty)\n  )\n)",
       "legendFormat": "{{source}} -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "${technology} requests (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 737 },
     "repeat": "technology",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  edges_regular = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace!~\"$excl_namespace\",\n          target_namespace!=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace!=\"empty\"\n        },\n        \"source_pod\", \"source\", \"target_pod\", \"target\"\n      ),\n      \"actual_destination\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  edges_empty = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace=\"empty\"\n        },\n        \"source_pod\", \"source\", \"actual_destination\", \"target\"\n      ),\n      \"target_pod\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  metric = max by (source, actual_destination) (\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_total\", container_id=~\"\\\\/k8s\\\\/[^\\\\/]+\\\\/[^\\\\/]+\\\\/.*\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/k8s\\\\/[^\\\\/]+\\\\/([^\\\\/]+)\\\\/.*\"\n      )\n    )\n    or\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_total\", container_id=~\"\\\\/system\\\\.slice\\\\/.*\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/system\\\\.slice\\\\/([^\\\\/]+)$\"\n      )\n    )\n  )\n)\n\ntopk_max(\n  $top,\n  (\n    metric\n    * on(source, actual_destination)\n    group_left(id, target, target_namespace, target_pod, target_service)\n    (edges_regular or edges_empty)\n  )\n)",
       "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    },
    {
     "title": "${technology} FAILED requests (shows the $top most frequent requests)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 744 },
     "repeat": "technology",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "WITH (\n  edges_regular = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace!~\"$excl_namespace\",\n          target_namespace!=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace!=\"empty\"\n        },\n        \"source_pod\", \"source\", \"target_pod\", \"target\"\n      ),\n      \"actual_destination\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  edges_empty = group by (source, actual_destination, target_namespace, target_pod, target_service, target, id) (\n    label_replace(\n      label_copy(\n        coroot:statefuls{\n          source_cluster_name=~\"$cluster\",\n          source_namespace=~\"$namespace\",\n          source_service=~\".*\",\n          target_namespace=\"empty\"\n        }\n        or on (source_pod, actual_destination)\n        coroot:statefuls{\n          target_namespace=~\"$namespace\",\n          target_service=~\".*\",\n          source_namespace=~\"$namespace\",\n          target_namespace=\"empty\"\n        },\n        \"source_pod\", \"source\", \"actual_destination\", \"target\"\n      ),\n      \"target_pod\", \"$1\", \"actual_destination\", \"(.+?)\"\n    )\n  ),\n  metric = max by (source, actual_destination, status) (\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_total\", container_id=~\"\\\\/k8s\\\\/[^\\\\/]+\\\\/[^\\\\/]+\\\\/.*\", status!~\"(ok|unknown)\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/k8s\\\\/[^\\\\/]+\\\\/([^\\\\/]+)\\\\/.*\"\n      )\n    )\n    or\n    (\n      label_replace(\n        rate({__name__=~\"container_${technology}_(queries|requests)_total\", container_id=~\"\\\\/system\\\\.slice\\\\/.*\", status!~\"(ok|unknown)\"})\n        [$__rate_interval],\n        \"source\", \"$1\", \"container_id\", \"\\\\/system\\\\.slice\\\\/([^\\\\/]+)$\"\n      )\n    )\n  )\n)\n\ntopk_max(\n  $top,\n  (\n    metric\n    * on(source, actual_destination)\n    group_left(id, target, target_namespace, target_pod, target_service)\n    (edges_regular or edges_empty)\n  )\n)",
       "legendFormat": "{{source}} (code:{{status}}) -> [{{target_namespace}}] {{target_pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\nalias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id,sample,level,pattern_hash) (\n      label_replace(\n        increase(\n          sum by (sample,level,pattern_hash,container_id) (rate(container_log_messages_total{container_id=~\"\\\\/k8s.*\", sample!=\"\"})) >0[1m]\n        )\n        ,\"id\",\"$1\",\"container_id\",\"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      )\n    ) \n  ,\"nodes\")\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs (shows the $top most frequent logs)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "WITH( \n    base_query = alias(\n    union(\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n        ),\n        (\n        group by (id,title,subtitle) (\n            label_join(\n                label_copy(\n                    coroot:success_connections{source_namespace=~\"$namespace\", source_service=~\"$service\", target_namespace!~\"$excl_namespace\"}\n                    , \"target_pod\",\"id\", \"target_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"target_namespace\",\"target_service\")\n                or \n            label_join(\n                label_copy(\n                    coroot:success_connections{target_namespace=~\"$namespace\", target_service=~\"$service\", source_namespace!~\"$excl_namespace\"}\n                    , \"source_pod\",\"id\", \"source_pod\",\"title\"\n                ),\n            \"subtitle\",\" \", \"source_namespace\",\"source_service\")\n            )\n        )\n    )\n,\"nodes\") )\n\n\ntopk_max($top,alias(base_query * on(id) group_right(title,subtitle,__name__) \n    sum by (id,sample,level,pattern_hash) (\n      label_replace(\n        increase(\n          sum by (sample,level,pattern_hash,container_id) (increase(container_log_messages_total{container_id=~\"\\\\/k8s.*\", sample!=\"\"})) >0[15s]\n        )\n        ,\"id\",\"$1\",\"container_id\",\"\\\\/k.+?\\\\/.*\\\\/(.+?)\\\\/.*\"\n      )\n    ) \n  ,\"nodes\"))\n",
     "legendFormat": "{{id}} ({{title}} {{subtitle}}) [{{level}}]: -----> {{sample}} "
    }
   ]
  }
 ]
}